# Generated by Django 3.2 on 2021-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('timeline', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
